package nl.dirkgroot.structurizr.dsl.lexer

import com.intellij.psi.tree.IElementType
import nl.dirkgroot.structurizr.dsl.psi.SDTypes.*

val KEYWORDS_WITH_BLOCKS = listOf(
    "!adrs" to ADRS_KEYWORD,
    "!constant" to CONSTANT_KEYWORD,
    "!docs" to DOCS_KEYWORD,
    "!identifiers" to IDENTIFIERS_KEYWORD,
    "!impliedRelationships" to IMPLIED_RELATIONSHIPS_KEYWORD,
    "!include" to INCLUDE_FILE_KEYWORD,
    "!plugin" to PLUGIN_KEYWORD,
    "!ref" to REF_KEYWORD,
    "->" to RELATIONSHIP_KEYWORD,
    "animation" to ANIMATION_KEYWORD,
    "autoLayout" to AUTO_LAYOUT_KEYWORD,
    "background" to BACKGROUND_KEYWORD,
    "border" to BORDER_KEYWORD,
    "color" to COLOR_KEYWORD,
    "colour" to COLOUR_KEYWORD,
    "component" to COMPONENT_KEYWORD,
    "container" to CONTAINER_KEYWORD,
    "containerInstance" to CONTAINER_INSTANCE,
    "custom" to CUSTOM_KEYWORD,
    "deployment" to DEPLOYMENT_KEYWORD,
    "deploymentEnvironment" to DEPLOYMENT_ENVIRONMENT_KEYWORD,
    "deploymentGroup" to DEPLOYMENT_GROUP_KEYWORD,
    "deploymentNode" to DEPLOYMENT_NODE_KEYWORD,
    "description" to DESCRIPTION_KEYWORD,
    "dynamic" to DYNAMIC_KEYWORD,
    "element" to ELEMENT_KEYWORD,
    "enterprise" to ENTERPRISE_KEYWORD,
    "exclude" to EXCLUDE_ELEMENT_KEYWORD,
    "extends" to EXTENDS_KEYWORD,
    "filtered" to FILTERED_KEYWORD,
    "fontSize" to FONTSIZE_KEYWORD,
    "group" to GROUP_KEYWORD,
    "healthCheck" to HEALTH_CHECK_KEYWORD,
    "height" to HEIGHT_KEYWORD,
    "icon" to ICON_KEYWORD,
    "include" to INCLUDE_ELEMENT_KEYWORD,
    "infrastructureNode" to INFRASTRUCTURE_NODE_KEYWORD,
    "instances" to INSTANCES_KEYWORD,
    "metadata" to METADATA_KEYWORD,
    "model" to MODEL_KEYWORD,
    "opacity" to OPACITY_KEYWORD,
    "person" to PERSON_KEYWORD,
    "perspectives" to PERSPECTIVES_KEYWORD,
    "position" to POSITION_KEYWORD,
    "routing" to ROUTING_KEYWORD,
    "shape" to SHAPE_KEYWORD,
    "softwareSystem" to SOFTWARE_SYSTEM_KEYWORD,
    "softwareSystemInstance" to SOFTWARE_SYSTEM_INSTANCE_KEYWORD,
    "stroke" to STROKE_KEYWORD,
    "strokeWidth" to STROKEWIDTH_KEYWORD,
    "style" to STYLE_KEYWORD,
    "styles" to STYLES_KEYWORD,
    "systemContext" to SYSTEM_CONTEXT_KEYWORD,
    "systemLandscape" to SYSTEM_LANDSCAPE_KEYWORD,
    "tags" to TAGS_KEYWORD,
    "technology" to TECHNOLOGY_KEYWORD,
    "theme" to THEME_KEYWORD,
    "thickness" to THICKNESS_KEYWORD,
    "title" to TITLE_KEYWORD,
    "url" to URL_KEYWORD,
    "views" to VIEWS_KEYWORD,
    "width" to WIDTH_KEYWORD,
    "workspace" to WORKSPACE_KEYWORD,
)

val KEYWORDS_WITH_PROPERTY_BLOCKS = listOf<Pair<String, IElementType>>(
    "branding" to BRANDING_KEYWORD,
    "configuration" to CONFIGURATION_KEYWORD,
    "properties" to PROPERTIES_KEYWORD,
    "terminology" to TERMINOLOGY_KEYWORD,
    "users" to USERS_KEYWORD,
)

val KEYWORDS = KEYWORDS_WITH_BLOCKS + KEYWORDS_WITH_PROPERTY_BLOCKS + listOf("!script" to SCRIPT_KEYWORD)
