package nl.dirkgroot.structurizr.dsl.lexer

import com.intellij.psi.tree.IElementType
import nl.dirkgroot.structurizr.dsl.psi.SDTypes.*

val KEYWORDS_WITH_BLOCKS = listOf(
    "!adrs" to UNQUOTED_TEXT,
    "!constant" to UNQUOTED_TEXT,
    "!docs" to UNQUOTED_TEXT,
    "!identifiers" to UNQUOTED_TEXT,
    "!impliedRelationships" to UNQUOTED_TEXT,
    "!include" to UNQUOTED_TEXT,
    "!plugin" to UNQUOTED_TEXT,
    "!ref" to UNQUOTED_TEXT,
    "autoLayout" to UNQUOTED_TEXT,
    "background" to UNQUOTED_TEXT,
    "border" to UNQUOTED_TEXT,
    "branding" to UNQUOTED_TEXT,
    "color" to UNQUOTED_TEXT,
    "colour" to UNQUOTED_TEXT,
    "component" to UNQUOTED_TEXT,
    "configuration" to UNQUOTED_TEXT,
    "container" to UNQUOTED_TEXT,
    "containerInstance" to UNQUOTED_TEXT,
    "custom" to UNQUOTED_TEXT,
    "deployment" to UNQUOTED_TEXT,
    "deploymentEnvironment" to UNQUOTED_TEXT,
    "deploymentGroup" to UNQUOTED_TEXT,
    "deploymentNode" to UNQUOTED_TEXT,
    "description" to UNQUOTED_TEXT,
    "dynamic" to UNQUOTED_TEXT,
    "element" to UNQUOTED_TEXT,
    "enterprise" to UNQUOTED_TEXT,
    "exclude" to UNQUOTED_TEXT,
    "extends" to UNQUOTED_TEXT,
    "filtered" to UNQUOTED_TEXT,
    "fontSize" to UNQUOTED_TEXT,
    "group" to UNQUOTED_TEXT,
    "healthCheck" to UNQUOTED_TEXT,
    "height" to UNQUOTED_TEXT,
    "icon" to UNQUOTED_TEXT,
    "include" to UNQUOTED_TEXT,
    "infrastructureNode" to UNQUOTED_TEXT,
    "instances" to UNQUOTED_TEXT,
    "metadata" to UNQUOTED_TEXT,
    "model" to UNQUOTED_TEXT,
    "opacity" to UNQUOTED_TEXT,
    "person" to UNQUOTED_TEXT,
    "position" to UNQUOTED_TEXT,
    "routing" to UNQUOTED_TEXT,
    "shape" to UNQUOTED_TEXT,
    "softwareSystem" to UNQUOTED_TEXT,
    "softwareSystemInstance" to UNQUOTED_TEXT,
    "stroke" to UNQUOTED_TEXT,
    "strokeWidth" to UNQUOTED_TEXT,
    "style" to UNQUOTED_TEXT,
    "styles" to UNQUOTED_TEXT,
    "systemContext" to UNQUOTED_TEXT,
    "systemLandscape" to UNQUOTED_TEXT,
    "tags" to UNQUOTED_TEXT,
    "technology" to UNQUOTED_TEXT,
    "terminology" to UNQUOTED_TEXT,
    "theme" to UNQUOTED_TEXT,
    "thickness" to UNQUOTED_TEXT,
    "title" to UNQUOTED_TEXT,
    "url" to UNQUOTED_TEXT,
    "views" to UNQUOTED_TEXT,
    "width" to UNQUOTED_TEXT,
    "workspace" to UNQUOTED_TEXT,
)

val KEYWORDS_WITH_PROPERTY_BLOCKS = listOf<Pair<String, IElementType>>(
    "perspectives" to UNQUOTED_TEXT,
    "properties" to UNQUOTED_TEXT,
    "users" to UNQUOTED_TEXT,
)

val KEYWORDS = KEYWORDS_WITH_BLOCKS + KEYWORDS_WITH_PROPERTY_BLOCKS +
    listOf("!script" to UNQUOTED_TEXT, "animation" to UNQUOTED_TEXT)
